### ISSUE TITLE
文档上 可以加一个部署教程吗 谢谢

### ISSUE THREAD

**Issue by zh1011** [Tencent/wujie#199]
**描述bug**
清晰准确的描述bug

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by rainxia2022** [comment]
顶，需要部署文档

**Comment by zhangmra** [comment]
顶，特别需要一个部署文档的教程，现在本地能用，nginx部署 主应用切换子应用就报错，跨域什么的也都加上了无解了呜呜呜

Error handling response: Error: Blocked a frame with origin "https://wujie-micro.github.io" from accessing a cross-origin frame.
    at tryShowingMateBar (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:5428:57)
    at eval (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:153:17)
    at eval (eval at success (chrome-extension://ihmgiclibbndffejedjimfjmfoabpcke/src/kernel/kernel.js:233:37), <anonymous>:108:27)

**Comment by n0mer** [comment]
This is mate translate extension: https://chromewebstore.google.com/detail/mate-translate-%E2%80%93-translat/ihmgiclibbndffejedjimfjmfoabpcke
