### ISSUE TITLE
F5刷新主应用 偶尔报错  Cannot read properties of null (reading 'document')

### ISSUE THREAD

**Issue by 107236074** [Tencent/wujie#281]
刷新页面时 偶尔出现报错 

Uncaught TypeError: Cannot read properties of null (reading 'document')
    at insertScriptToIframe (iframe.ts:680:38)
    at execScript2 (effect.ts:246:15)
    at effect.ts:263:27

![image](https://user-images.githubusercontent.com/46079969/203518282-950e3fc5-c7d1-41e9-b1ca-ba764614fd48.png)

**Comment by zhzhuang01** [comment]
我vue2接入，一直会出现这个错误。要怎么解决。。。但是渲染是正常的
