### ISSUE TITLE
nuxt如何集成wujie

### ISSUE THREAD

**Issue by PeterPanY** [Tencent/wujie#299]
如题，在nuxt中如何集成wujie呢？nuxt作为主应用、nuxt作为子应用？

**Comment by ErKeLost** [comment]
无界目前不支持服务端渲染

**Comment by yiludege** [comment]
对于 next 试试： https://blog.bitsrc.io/using-non-ssr-friendly-components-with-next-js-916f38e8992c

**Comment by yiludege** [comment]
对于 next 试试： https://blog.bitsrc.io/using-non-ssr-friendly-components-with-next-js-916f38e8992c

对于 nuxt 试试：https://nuxtjs.org/docs/features/nuxt-components#the-client-only-component

**Comment by gyhyfj** [comment]
@yiludege nextjs主应用，在客户端组件中，引入WujieReact报错：
```
error - node_modules\.pnpm\wujie-react@1.0.8_react@18.2.0\node_modules\wujie-react\lib\index.js (2:259) @ eval
error - ReferenceError: self is not defined
    at __webpack_require__ (D:\GitRepo\nextjs-app\.next\server\webpack-runtime.js:33:42)
    at eval (./src/app/generate/page.tsx:7:69)
    at Object.(sc_client)/./src/app/generate/page.tsx (D:\GitRepo\nextjs-app\.next\server\app\generate\page.js:1604:1)
    at __webpack_require__ (D:\GitRepo\nextjs-app\.next\server\webpack-runtime.js:33:42)
```
代码如下：
```
'use client'

import WujieReact from 'wujie-react'

// const { bus, setupApp, preloadApp, destroyApp } = WujieReact

export default function Page() {
  return (
    <>
      <WujieReact
        width="100%"
        height="100%"
        name="xxx"
        url={'//localhost:5173'}
        sync={true}
        // fetch={fetch}
        // props={props}
        // beforeLoad={beforeLoad}
        // beforeMount={beforeMount}
        // afterMount={afterMount}
        // beforeUnmount={beforeUnmount}
        // afterUnmount={afterUnmount}
      ></WujieReact>
    </>
  )
}

```

**Comment by sky124380729** [comment]
jsp支持吗？

**Comment by fyzhaha** [comment]
请问目前wujie支持集成到nuxt中了吗

**Comment by gyhyfj** [comment]
> 请问目前wujie支持集成到nuxt中了吗

无界没有支持，但nuxt写一个客户端组件就可以了，就是路由的处理有点烧脑。总之就是不推荐，甚至不如iframe

**Comment by fyzhaha** [comment]
> > 请问目前wujie支持集成到nuxt中了吗
> 
> 无界没有支持，但nuxt写一个客户端组件就可以了，就是路由的处理有点烧脑。总之就是不推荐，甚至不如iframe

请问是指将wujie的组件包在clientOnly组件里吗？
![image](https://github.com/Tencent/wujie/assets/35005130/b442fa1b-25af-457f-ae8b-defcb513e64e)

![image](https://github.com/Tencent/wujie/assets/35005130/ac8ee266-2e32-4d59-b9f5-76bce73c906f)

**Comment by fyzhaha** [comment]
> > 请问目前wujie支持集成到nuxt中了吗
> 
> 无界没有支持，但nuxt写一个客户端组件就可以了，就是路由的处理有点烧脑。总之就是不推荐，甚至不如iframe

请问是指将wujie的组件包在clientOnly组件里吗？
![image](https://github.com/Tencent/wujie/assets/35005130/87c4b04f-562e-48c4-952a-61d7da618501)
![image](https://github.com/Tencent/wujie/assets/35005130/41214204-5f43-49ec-9e66-77ffe8f2a9ac)

**Comment by gyhyfj** [comment]
> > > 请问目前wujie支持集成到nuxt中了吗
> > 
> > 
> > 无界没有支持，但nuxt写一个客户端组件就可以了，就是路由的处理有点烧脑。总之就是不推荐，甚至不如iframe
> 
> 请问是指将wujie的组件包在clientOnly组件里吗？ ![image](https://private-user-images.githubusercontent.com/35005130/308897076-87c4b04f-562e-48c4-952a-61d7da618501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjIzNDcsIm5iZiI6MTcwOTI2MjA0NywicGF0aCI6Ii8zNTAwNTEzMC8zMDg4OTcwNzYtODdjNGIwNGYtNTYyZS00OGM0LTk1MmEtNjFkN2RhNjE4NTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAzMDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2MTMxOTJkMGM5NzBlYTVhODdkYjU5Yzc1YWRmY2VlMDBiZTNlYTJkYzAwNjNjNzIzZWMyOTA0NWZhYmE4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OgbWJXZuCXR_ITJqxNJY4AjiOwh301cX2dckRmBqsYQ) ![image](https://private-user-images.githubusercontent.com/35005130/308897239-41214204-5f43-49ec-9e66-77ffe8f2a9ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjIzNDcsIm5iZiI6MTcwOTI2MjA0NywicGF0aCI6Ii8zNTAwNTEzMC8zMDg4OTcyMzktNDEyMTQyMDQtNWY0My00OWVjLTllNjYtNzdmZmU4ZjJhOWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDAzMDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjBkNDllNTMzZTcyZDBmMmY1NmFmZDFlNzMyY2U4NGM2MDNlMWY3ZTVlNzNjMmFlNTlmNThiZmRjZmRiNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O99A_oXL1cAn65tR-wezktm1PvyneBRXtY9EHspHx-I)

还需要处理js代码的引用，只要最终不报错就ok

**Comment by burakakca** [comment]
> @yiludegeIn the nextjs main application, in the client component, the WujieReact error is introduced:
> 
> ```
> error - node_modules\.pnpm\wujie-react@1.0.8_react@18.2.0\node_modules\wujie-react\lib\index.js (2:259) @ eval
> error - ReferenceError: self is not defined
>     at __webpack_require__ (D:\GitRepo\nextjs-app\.next\server\webpack-runtime.js:33:42)
>     at eval (./src/app/generate/page.tsx:7:69)
>     at Object.(sc_client)/./src/app/generate/page.tsx (D:\GitRepo\nextjs-app\.next\server\app\generate\page.js:1604:1)
>     at __webpack_require__ (D:\GitRepo\nextjs-app\.next\server\webpack-runtime.js:33:42)
> ```
> 
> The code is as follows:
> 
> ```
> 'use client'
> 
> import WujieReact from 'wujie-react'
> 
> // const { bus, setupApp, preloadApp, destroyApp } = WujieReact
> 
> export default function Page() {
>   return (
>     <>
>       <WujieReact
>         width="100%"
>         height="100%"
>         name="xxx"
>         url={'//localhost:5173'}
>         sync={true}
>         // fetch={fetch}
>         // props={props}
>         // beforeLoad={beforeLoad}
>         // beforeMount={beforeMount}
>         // afterMount={afterMount}
>         // beforeUnmount={beforeUnmount}
>         // afterUnmount={afterUnmount}
>       ></WujieReact>
>     </>
>   )
> }
> ```

I have same problem how can I fix that ?
