### ISSUE TITLE
子应用加载偶尔会出现startApp的错误回调， TypeError: Cannot read properties of undefined (reading 'appendChild')

### ISSUE THREAD

**Issue by makai1027** [Tencent/wujie#358]
**描述bug**
清晰准确的描述bug
TypeError: Cannot read properties of undefined (reading 'appendChild')
    at shadow.js:298:24
    at h (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at ev (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)

![image](https://user-images.githubusercontent.com/24761813/212818881-dbbcaa2d-a3ed-4dd2-8376-8340d310c820.png)
![image](https://user-images.githubusercontent.com/24761813/212818896-a328028a-8af0-4f8e-8b86-28a5086567ea.png)
<img width="969" alt="image" src="https://user-images.githubusercontent.com/24761813/212818912-73cce253-cbca-46f6-b9fc-8b0f196f0352.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/24761813/212818921-5841db28-8c31-4afe-9529-a2ce8a20c440.png">

该方法的错误回调无法触发loadError回调

**如何复现**
给出详细的复现步骤
这个也是偶尔出现，重新刷新加载即可，
有时会loading很久，
可能是网络问题

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度
期望能触发错误回调，方便后续操作

**Comment by makai1027** [comment]
mounted 回调函数内的 window. __WUJIE.el.childNodes[0].childNodes 是空的
但是 window. __WUJIE.template是正常的

**Comment by zyuexin** [comment]
遇到了相同的问题

**Comment by makai1027** [comment]
你是什么使用场景，用keep alive包了子应用的路由，子应用是保活模式？> 遇到了相同的问题

**Comment by chenhongen** [comment]
感觉这段代码有问题呢。this.shadowRoot空的 走 renderTemplateToShadowRoot 必然出现appendChild问题。
![image](https://user-images.githubusercontent.com/16499303/222676520-9d2214b0-2679-4e49-9381-513bfbf504e8.png)
