### ISSUE TITLE
element-plus 升级到 2.3.9 版本报错 Cannot read properties of null (reading 'emitsOptions')

### ISSUE THREAD

**Issue by songyihong** [Tencent/wujie#679]
**描述bug**
element-plus 升级到 2.3.9 版本报如下错误

runtime-core.esm-bundler.js:1082 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (runtime-core.esm-bundler.js:1082:29)
    at updateComponent (runtime-core.esm-bundler.js:5518:13)
    at processComponent (runtime-core.esm-bundler.js:5472:13)
    at patch (runtime-core.esm-bundler.js:5058:21)
    at patchBlockChildren (runtime-core.esm-bundler.js:5375:13)
    at Object.process (runtime-core.esm-bundler.js:6429:17)
    at patch (runtime-core.esm-bundler.js:5061:26)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5680:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5714:56)

**如何复现**
给出详细的复现步骤
1、基于你们 wujie 仓库代码，将 examples/vite 和 examples/vue3 element-plus 库升级到最新版本 2.3.9 然后启动
2.  打开应用，切换 vite/home 和 vite/dialog 菜单互相切换，第一次不会出现，点击第二次控制台将出现错误，vite/dialog 下来框就无法下拉了

**错误截图**
![WeChatWorkScreenshot_2f9dce9a-7562-4ee0-a7d4-e18018289293](https://github.com/Tencent/wujie/assets/1669169/6b799336-eaf3-49fa-a9f3-b9cb320175b3)

**最小复现仓库或者地址**
https://github.com/Tencent/wujie.git

**Comment by siYuanJun** [comment]
我也出现了，element-plus^2.2.19 这个版本也不行。需要换一种模式, 可以使用重建模式试一下。

**Comment by warmthsea** [comment]
这似乎不是 elp 的 bug ，你应该检查使用 v-if 的元素是否被销毁了

**Comment by Lisheri** [comment]
请问解决了吗, 我这里用el-select + el-options可以复现

**Comment by Lisheri** [comment]
2.7.7的版本

**Comment by warmthsea** [comment]
> 请问解决了吗, 我这里用el-select + el-options可以复现

https://github.com/element-plus/element-plus/issues
你可以在 issus 提供复现地址以及详细的问题报告

**Comment by Lisheri** [comment]
> > 请问解决了吗, 我这里用el-select + el-options可以复现
> 
> https://github.com/element-plus/element-plus/issues 你可以在 issus 提供复现地址以及详细的问题报告

单例模式二次加载的报错也给element吗= =重建模式就没问题

**Comment by warmthsea** [comment]
> > > 请问解决了吗, 我这里用el-select + el-options可以复现
> 
> > 
> 
> > https://github.com/element-plus/element-plus/issues 你可以在 issus 提供复现地址以及详细的问题报告
> 
> 
> 
> 单例模式二次加载的报错也给element吗= =重建模式就没问题

抱歉我没有说清楚，我的意思是如果是 elp的bug可以去提 issue，不是的话就不用

**Comment by Lisheri** [comment]
> > > > 请问解决了吗, 我这里用el-select + el-options可以复现
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/element-plus/element-plus/issues 你可以在 issus 提供复现地址以及详细的问题报告
> > 
> > 
> > 单例模式二次加载的报错也给element吗= =重建模式就没问题
> 
> 抱歉我没有说清楚，我的意思是如果是 elp的bug可以去提 issue，不是的话就不用

好的, 我提了一个新的issue, 看起来像是element-plus并没有跟随vue实例重新初始化...
![image](https://github.com/user-attachments/assets/dc33212b-a7ba-4791-9c8c-9400e70d3448)

**Comment by warmthsea** [comment]
可以提供可以不报错的 elp 的版本号么
@Lisheri

**Comment by Lisheri** [comment]
> 可以提供可以不报错的 elp 的版本号么 @Lisheri
目前测过2.3和2.7.7两个版本均报错, 但是看起来是和组件有关系, 像el-table就是正常的
