### ISSUE TITLE
主子应用都是Angular，子应用在使用MutationObserver用作动画处理时，zone.js中的patchClass的get方法陷入死循环

### ISSUE THREAD

**Issue by Arethusa2024** [Tencent/wujie#871]
**描述bug**
主子应用都是Angular，子应用在使用MutationObserver用作动画处理时，zone.js中的patchClass的get方法陷入死循环
Uncaught RangeError: Maximum call stack size exceeded
    at _global.<computed>.get (zone.js:931:25)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)
    at _global.<computed>.get (zone.js:931:32)

**如何复现**
给出详细的复现步骤
1、第一步 xxx
2、 第二步 xxx

**错误截图**
如果有可以将截图带上

**最小复现仓库或者地址**
重要！！！，请尽量给出复现仓库，这样能极大加快bug解决速度

**Comment by tmx-502** [comment]
请问楼主这个问题解决了吗  遇到同样问题 卡这里了
